### PR TITLE
Feature/bsd 212 smpt enable

### PR DESCRIPTION
**Pull request by mattsqd**

### CODE REVIEW

**Comment by mattsqd** [comment]
I'm waiting for https://github.com/Bixal/bixal-site-drupal/pull/233 to be merged so I can create a feature branch for this and it can be tested.
https://console.platform.sh/bixal-com-gerardo-maldonado/tsvj5tw7p3f66/main/settings/variables

**Comment by mattsqd** [comment]
@buddy-harlow Alright, this should be good to go:

Contact yourself here https://pr-234-vpaqoby-tsvj5tw7p3f66.us.platformsh.site/user/5/contact
and you should get the email and it should be logged https://pr-234-vpaqoby-tsvj5tw7p3f66.us.platformsh.site/admin/reports/maillog

**Comment by buddy-harlow** [comment]
@mattsqd Sorry about the delay on this, https://pr-234-vpaqoby-tsvj5tw7p3f66.us.platformsh.site/user/5/contact says access denied now

**Review by buddy-harlow — APPROVED** [review]
APPROVED!

**Pull request merged**
