### PR TITLE
Feature/bsd 3 local env

### PR DESCRIPTION
**Pull request by mpbixal**
Created a local and remote environment.

Can be seen at https://pr-9-anm2a6y-tsvj5tw7p3f66.us.platformsh.site/

admin / admin is the u/p.

Can be tested locally with:

`lando start & lando si`

The front end uses node 18 and will be built in `orch/build_fe_shared.sh`

Lots more functionality to come.

### CODE REVIEW

**Review by buddy-harlow — APPROVED** [review]
Looks good Matt, however I had an issue starting the first time with composer. When I ran start, then si, si didn't work, so I ran a rebuild if I remember correctly and now everything's cool. I'll approve and keep you notified if I run into any other issues.

**Review by mejiaj — COMMENTED** [review]
Admittedly, it's been a minute since I've setup a Drupal project (aside from the Drupal Bixal theme).

### Build attempt 3

Downgraded lando to 3.19.5.

Now I see this on `lando start`:

```bash
  ⚠ BIXALCOM URLS
    ✖ http://localhost:65287 [500] - REQUEST FAILED WITH STATUS CODE 500
    ✔ http://bixalcom.lndo.site/ [404]
    ✔ https://bixalcom.lndo.site/ [404]
```

---

**Sytem info**

- **Lando version:** ~v3.20.4~ 3.19.5
- **Docker version:** 24.0.7, build afdd53b4e3
- **System info:** M1 Macbook pro

**Review by mejiaj — APPROVED** [review]
Works great now. Site successfully builds and runs with changes done in [0f8e1b3](https://github.com/Bixal/bixal-site-drupal/pull/9/commits/0f8e1b3c3cd56e7eb287fb8fce71b99947855e52).

**Review by buddy-harlow — APPROVED** [review]
Works as expected; Thanks Matt!

**Pull request merged**
