### PR TITLE
Closes #64 robo validate

### LINKED ISSUE #64: Apply settings for robo validate
Configure the robo.yml so that robo validate can be run locally and eventually in the pipelines.

### PR DESCRIPTION
**Pull request by mpbixal**
This MR implements validation commands which will eventually be run in a pipeline.
You can run these locally by:

`vendor/bin/robo validate:all`

I've also fixed a couple coding standards issues.

Please note that commit messages soon will be required to be in the form:
BSD [KEYWORD] #x:y
Where x is the Git Hub issue number.
And y is a space.
The keywords are: close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved

Feature branches will also be in the form:
feature/{BSD-x-y
Where x is the issue number and y is a short description lower case.

### CODE REVIEW

**Comment by mejiaj** [comment]
Suggesting edits for additional clarification…

## Commit messages

>Please note that commit messages soon will be required to be in the form:
>BSD [KEYWORD] #x:y
>Where x is the Git Hub issue number.
>And y is a space.
>The keywords are: close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved

**Commit messages**

> [!IMPORTANT]  
> Note the space **before** the description.

`BSD [KEYWORD] #[ISSUE_NUMBER]: [DESCRIPTION]`.

Available keywords: `close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved`.

Example: `BSD fixes #64: Fixed coding standards issues.`


## Branch naming standards

>Feature branches will also be in the form:
>feature/{BSD-x-y
>Where x is the issue number and y is a short description lower case.

**Feature branches**
`feature/BSD-[ISSUE_NO]-[LOWER_CASE_DESCRIPTION]`

Example: `feature/BSD-11-robo-validate`.

**Review by mejiaj — COMMENTED** [review]
@mpbixal suggesting edits to PR description for additional clarification…

## Commit messages

>Please note that commit messages soon will be required to be in the form:
>BSD [KEYWORD] #x:y
>Where x is the Git Hub issue number.
>And y is a space.
>The keywords are: close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved

**Commit messages**

> [!IMPORTANT]  
> Note the space **before** the description.

`BSD [KEYWORD] #[ISSUE_NUMBER]: [DESCRIPTION]`.

Available keywords: `close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved`.

Example: `BSD fixes #64: Fixed coding standards issues.`


## Branch naming standards

>Feature branches will also be in the form:
>feature/{BSD-x-y
>Where x is the issue number and y is a short description lower case.

**Feature branches**
`feature/BSD-[ISSUE_NO]-[LOWER_CASE_DESCRIPTION]`

Example: `feature/BSD-11-robo-validate`.

**Comment by mpbixal** [comment]
Thanks @mejiaj ! I've updated the template and you can see the full output here:

COMMIT MESSAGES:
image

BRANCH NAME:
image

**Review by mejiaj — APPROVED** [review]
Guidance looks great!

**Review by buddy-harlow — APPROVED** [review]
Looks great and functions as expected. Tested it by making some horrendous commits on a branch I checked out from this one called 'bad'.

**Pull request merged**
