### PR TITLE
Feature - BDS-1: Create styleguide

### LINKED ISSUE #1: Create site styleguide
Collect Bixal site components to audit and apply consistent styles.

**Identified components**

- [x] Button
- [x] Typography
- [x] Multi column list (_ex: [Careers benefits list](https://www.bixal.com/careers/#:~:text=COMPETITIVE%20BASE%20SALARY,WITH%20EMPLOYER%20MATCH)_)
- [x] Description list
- [x] Hero
- [x] Callout section
- [x] Flippy cards
- [x] Header
- [x] Footer
- [x] Form elements (Contact us)
- [x] Contact us form
- [x] Emphasis block (_ex: [job block](https://www.bixal.com/careers/#:~:text=VIEW%20ALL%20JOBS-,Featured%20Jobs,-STRATEGIC%20GROWTH)_)
- [x] Image list (_ex: [people list](https://www.bixal.com/about/#:~:text=empathy%20and%20understanding.-,Meet%20Team%20Bixal,-An%20organization%20is)_)
- [x] Profile (_ex: https://www.bixal.com/about/brad-mash/_) 
- [x] Pillar (_ex: [Pillar](https://www.bixal.com/about/#:~:text=People%2Dabsolutely%2Dfirst.,across%20our%20entire%20team.)_)

### Todo

As a follow-up. Also need to breakdown Case Studies, both list and individual.

- https://www.bixal.com/our-work/
- https://www.bixal.com/our-work/digital-apex/
- [Icon list](https://www.bixal.com/our-work/hhs/#:~:text=Drupal%209%2C%20USAJOBS%20API%2C%20React.js%2C%20Leaflet%20Map%20API)
- Blog columns (Like pillar, but clickable. Ex: https://www.bixal.com/blog/)
- [Key points](https://www.bixal.com/contract-vehicles/eval-me-ii-idiq)

### PR DESCRIPTION
**Pull request by mejiaj**
**New component library powered by StorybookJS and twig.** Documents most components with simpler markup, CSS variables, and USWDS tokens.

This work uses USWDS tokens and Twig templates.

Closes #1.

## How to test

- Checkout branch
- Run `npm install` in terminal
- Run `npm start`
- Visit `http://localhost:6008`

You should see a component library with common site components.

### CODE REVIEW

**Review by buddy-harlow — DISMISSED** [review]
Hey James, all these components look great and really capture what's already on the site. Excited to see how we're going to incorporate these into drupal!

My only notes are that spacing on some of the elements are a little off currently. Like distance between first form element in contact form and the header above it, the centered callout needs extra headroom for that black text on that image to be effective. Just noting the ones I saw, but the turnaround on this is awesome so we'll refine when it comes time.

**Comment by mejiaj** [comment]
> Hey James, all these components look great and really capture what's already on the site. Excited to see how we're going to incorporate these into drupal!
> 
> My only notes are that spacing on some of the elements are a little off currently. Like distance between first form element in contact form and the header above it, the centered callout needs extra headroom for that black text on that image to be effective. Just noting the ones I saw, but the turnaround on this is awesome so we'll refine when it comes time.

Thanks for the review @buddy-harlow. Yes, I intentionally left it that way. There were inconsistencies found with heading styles, so I opted for this for now. As we build out pages I'd like to address via a more consistent solution.

**Comment by mpbixal** [comment]
@mejiaj I updated the code slightly so that story book could run in docker without needing to have node locally. If you don't like, simply revert my last commit to your branch.
Now you can just start up lando and go to http://storybook.bixalcom.lndo.site/. You'll need to lando rebuild -y first to pick up the changes.

**Comment by mejiaj** [comment]
> @mejiaj I updated the code slightly so that story book could run in docker without needing to have node locally. If you don't like, simply revert my last commit to your branch. Now you can just start up lando and go to http://storybook.bixalcom.lndo.site/. You'll need to lando rebuild -y first to pick up the changes.

Thank you for doing this, it looks good!

**Review by mpbixal — APPROVED** [review]

**Pull request merged**
