### PR TITLE
BSD fixes #54: Allow contact us form to be functional.

### LINKED ISSUE #54: Make 'Contact Us' component functional
1. Determine what functionality the contact form should have:

- Does it send email? Does it store submissions

2. Given 1, what should power it?

- Core contact module, web form, other?

3. Given this form is created in storybook how do integrate the two so that storybook drives the design and when it updates Drupal updates but that it is functional?

- Are there confirmation pages that need components as well?

### PR DESCRIPTION
**Pull request by mpbixal**
* Works for both anonymous and logged in users
* Logged in users have a disabled name and email field and it uses their profile info, used text fields so that it fit the same layout instead of plain text 
* Use http://mailhog.bixalcom.lndo.site/ to see the emails it sends
* You must set a recipient here http://bixalcom.lndo.site/admin/structure/contact/manage/site_wide because I made that ignored configuration (so they can change it themselves without it getting removed by a deployment).

Known issues:
* Submit button does not have the right arrow on it, it would have been too much effort to figure out how to get that when not in a template.
* First name + Last name fields are just a single 'Name' field. This is how the built in Contact module expects it to be and it would be a ton of overriding to change.

### CODE REVIEW

**Comment by mpbixal** [comment]
@mejiaj I was not able to use the contact-us template at all because of all the functionality that is needed for forms, instead I used your classes and attributes and added them to my Drupal form elements. Because of this, changes to the template in SB will not effect Drupal, but the CSS will.

**Review by buddy-harlow — CHANGES_REQUESTED** [review]
I believe you may have to add this file to config ignore. Upon installation your email showed up in this form for me.

config/sync/contact.form.site_wide.yml

**Comment by mpbixal** [comment]
> I believe you may have to add this file to config ignore. Upon installation your email showed up in this form for me.
> 
> config/sync/contact.form.site_wide.yml

This was actually on purpose, but sneaky. I did not config ignore the entire site_wide settings. I had to have it install the contact form, but I wanted the important settings to be ignored. So you can change the recipients or the message and a deploy will not wipe that out, but if you were to delete the contact form, it would come back (without those sub settings).

**Comment by mpbixal** [comment]
@buddy-harlow I think it's find that it loads with my email there, that way there is at least some value and it will alert us if they don't change it. I think how config ignore works, is that the initial config import, the config makes it through, but once the config ignore is imported itself, it will no longer import.
You can test this by changing both the label and the recipients and saving. When you cim, the label will revert, the recipients will not.

**Pull request merged**
